name: dartarabic
description: Parsing Arabic text
version: 0.0.1
homepage: https://github.com/thexaib/dartarabic

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  string_validator: ^0.1.4
  characters: ^1.1.0-nullsafety.5
  unicode_data: ^0.1.1

dev_dependencies:
  test: ^1.16.4
