name: dartarabic
description: A specific Arabic language library ported to dart from Python, provides basic functions to manipulate Arabic letters and text.
version: 0.1.0
homepage: https://github.com/thexaib/dartarabic

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  string_validator: ^0.3.0
  characters: ^1.2.1

dev_dependencies:
  test: ^1.16.4
