name: dartarabic
description: Parsing Arabic text. A specific Arabic language library ported to dart from Python, provides basic functions to manipulate Arabic letters and text remove diacritics, normalize ligature etc.
version: 0.0.1-dev3
homepage: https://github.com/thexaib/dartarabic

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  string_validator: ^0.1.4
  characters: ^1.1.0-nullsafety.5
  unicode_data: ^0.1.1

dev_dependencies:
  test: ^1.16.4
  isolate: ^2.0.3
