name: dartarabic
description: A specific Arabic language library ported to dart from Python, provides basic functions to manipulate Arabic letters and text.
version: 0.3.1
homepage: https://github.com/thexaib/dartarabic

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  string_validator: ^1.1.0
  characters: ^1.3.0

dev_dependencies:
  test:
